### ISSUE TITLE
挂3天以上就会报错

### ISSUE THREAD

**Issue by 493Arceus** [NeverBehave/BilibiliHelper#2]
`PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: connect() timed out! (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /root/BilibiliHelper/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185`
`Stack trace:`
`#0 /root/BilibiliHelper/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)`
`#1 /root/BilibiliHelper/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))`
`#2 /root/BilibiliHelper/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))`
`#3 /root/BilibiliHelper/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(Guz in /root/BilibiliHelper/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185`

是php版本大于7.0的问题么

**Comment by NeverBehave** [comment]
@493Arceus 请关闭小电视功能后尝试

**Comment by 493Arceus** [comment]
好的我试试

**Comment by 493Arceus** [comment]
呃……小电视百分比是为0的

**Comment by metowolf** [comment]
这是由于连接 API 超时导致的，可以查看报错上一条的 debug 信息来定位

**Comment by 493Arceus** [comment]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097160 bytes) in /root/BilibiliHelper/vendor/wrench/wrench/lib/Wrench/Client.php on line 145

- -现在变成这样了
